### PR TITLE
Add available commands to documentation

### LINKED ISSUE #6: Document available `npm` commands
Documentation for available `npm` commands (`test`, `test:schema`, …) should be added in the declarations repositories README.

### PR DESCRIPTION
**Pull request by martinratinaud**
Fixes #6

### CODE REVIEW

**Review by MattiSG — CHANGES_REQUESTED** [review]
This is not what is described in #6. Here, we want to document the npm scripts that are provided in the collection modules, not the CLI of `opentermsarchive`.

**Comment by martinratinaud** [comment]
@MattiSG my bad, I did not read the issue properly.

The ota commands are still available from the command line
Screen Shot 2023-02-08 at 10 05 43

So i'm wondering if having all this npm scripts is really relevant anymore, as they are just shortcuts to existing commands (except for `start:modified`)

Maybe we should discuss if they are needed afterall

In case, they are, I can add this, with a link to the proper documentation in OTA engine, in order to not have the doc stored in two places ?
- `npm run lint`
- `npm run test`
- `npm run test:schema`
- `npm run test:modified`
- `npm run start`
- `npm run start:schedule`
- `npm run start:modified`
- `npm run dataset`
- `npm run dataset:schedule`

Does it sound more relevant ?

**Comment by MattiSG** [comment]
I believe the `ota` command is available for you only because it was installed globally on your machine 🙂 You can check this with `whereis ota`.
We can either document that the commands are available in `node_modules/.bin/ota` and then link to the doc, or keep on maintaining this wrapper script.
The pro of the wrapper script is that it shields reusers from changes to the CLI; the cons are that it does not familiarise them with the CLI, and that it adds some maintenance burden on our side.

It might thus be better to end with just referencing `node_modules/.bin/ota`. However, at this stage, I see the following reasons to stick with the wrapper scripts:

1. `start:modified` is way too complex and not provided by the `ota` CLI. It is thus either to be wrapped, or to be dropped. If we keep it wrapped, I find it very confusing for reusers to document that “in all of these cases, use the `ota` command line, except in that one case”.
2. `dataset:schedule` is quite a specific combination of options, while it is also the main entry point of every collection. I am not sure we really want to pass all these options in every deployment script.
3. `npm test` is a lifecycle script, having it as an entry point is useful for compliance with standard ecosystem tools. This might not be absolutely relevant though, since collection modules are not meant to be published for the moment.

If you trust in our implementation of `validate:modified` in Open Terms Archive and can replicate it for `start:modified` as a simple `ota track --modified` option, then we might get rid of the wrapper scripts 🙂 Otherwise, I believe we should stick with them.

**Comment by martinratinaud** [comment]
Well noted @MattiSG and I agree.
We already considered adding `--modified` to `ota track` within the core but decided not to as it added a lot of logic we did not want to happen in the `src/index.js` file

I pushed a new version of the documentation with enough info to understand what it's for at first glance and link to more info.

**Review by MattiSG — APPROVED** [review]
Looks good, thanks! 🙂 

Potential improvements:
- add a `.` after each link to documentation to have proper punctuation
- add a newline after the `###` titles

**Pull request merged**
